version: 2.1
orbs:
    node: circleci/node@5.0.2

jobs:
    deploy:
        docker:
            - image: cimg/deploy:2022.09.1-node
        steps:
            - checkout
            - run:
                  name: zip function
                  command: |
                      zip helloworld.zip index.js

            - store_artifacts:
                  path: helloworld.zip

            - run:
                  name: terraform plan
                  command: |
                      terraform init -input=false
                      terraform plan -input=false -compact-warnings -out=plan.file

            - store_artifacts:
                  path: plan.file

            - run:
                  name: terraform apply
                  command: |
                      terraform apply -input=false -compact-warnings "plan.file"

workflows:
    build:
        jobs:
            - deploy
